// <auto-generated />
using KCIAO.API.MVC.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace KCIAO.API.MVC.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KCIAO.API.MVC.Models.ClienteModel", b =>
                {
                    b.Property<string>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("nm_cliente")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id_cliente");

                    b.ToTable("tb_cliente");
                });

            modelBuilder.Entity("KCIAO.API.MVC.Models.ConsultaModel", b =>
                {
                    b.Property<string>("id_consulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("horario_consulta")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("local_consulta")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("profissional")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id_consulta");

                    b.ToTable("tb_consulta");
                });

            modelBuilder.Entity("KCIAO.API.MVC.Models.DoencaModel", b =>
                {
                    b.Property<string>("id_doenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("nm_doenca")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id_doenca");

                    b.ToTable("tb_doenca");
                });

            modelBuilder.Entity("KCIAO.API.MVC.Models.EventoModel", b =>
                {
                    b.Property<string>("id_evento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("desc_evento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("dt_evento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("tipo_evento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id_evento");

                    b.ToTable("tb_evento");
                });
#pragma warning restore 612, 618
        }
    }
}
